### ISSUE TITLE
After updating to 1.0.5 type `com.amitshekhar.DebugDB` not available

### ISSUE THREAD

**Issue by fjna** [amitshekhariitbhu/Android-Debug-Database#149]
As implied in the title, after updating to the latest version I can't use `com.amitshekhar.DebugDB` to access `DebugDB.getAddressLog()`

I am importing as follows: `debugImplementation 'com.amitshekhar.android:debug-db:1.0.5'`

**Comment by laxmisalunkhe** [comment]
I am also facing this same issue, Can anyone share any fix for this?

**Comment by amitshekhariitbhu** [comment]
Fixing in 1-2 days

**Comment by amitshekhariitbhu** [comment]
@fjna @laxmisalunkhe 
Thanks for pointing it out. I have fixed it in the new version

### Using Android Debug Database Library in your application

Add this to your app's build.gradle

```groovy
debugImplementation 'com.amitshekhar.android:debug-db:1.0.6'
```

Using the Android Debug Database with the encrypted database

```groovy
debugImplementation 'com.amitshekhar.android:debug-db-encrypt:1.0.6'
```

**Comment by laxmisalunkhe** [comment]
@amitshekhariitbhu Issue still exist after upgrading new version.

**Comment by amitshekhariitbhu** [comment]
@amitshekhariitbhu In prod or debug build?

**Comment by amitshekhariitbhu** [comment]
@laxmisalunkhe In release or debug build?

**Comment by laxmisalunkhe** [comment]
@amitshekhariitbhu debug build
